In [1]:
cd ..

/home/avani/src

In [2]:
pwd

'/home/avani/src'

In [3]:
from utils import calc_third_quartile, get_unique_act, get_compliant_cases 
import numpy as np
import os
import pickle
import pandas as pd
import random
from statistics import mean, median

In [4]:
dataset = "traffic_ss"
df2 = pd.read_pickle('dataset/preprocessed/'+dataset+'_design_mat.pkl')

In [5]:
df2

,0,1,2,3,4,5,6,7,8,9,10,11,duration_time,remaining_time,class,CaseID
0,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,740.958333,1,1
1,0,0,1,0,0,0,0,0,0,0,0,0,118.958333,622.000000,2,1
2,0,0,0,1,0,0,0,0,0,0,0,0,16.000000,606.000000,3,1
3,0,0,0,0,1,0,0,0,0,0,0,0,60.000000,546.000000,4,1
4,0,0,0,0,0,1,0,0,0,0,0,0,546.000000,0.000000,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56383,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,1,15037
56384,0,0,1,0,0,0,0,0,0,0,0,0,0.000000,442.041667,2,15037
56385,0,0,0,1,0,0,0,0,0,0,0,0,6.041667,436.000000,3,15037
56386,0,0,0,0,1,0,0,0,0,0,0,0,60.000000,376.000000,4,15037
56387,0,0,0,0,0,1,0,0,0,0,0,0,376.000000,0.000000,5,15037

In [6]:
# get process flow compliance cases only
df = get_compliant_cases(df2,dset=dataset)

In [7]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,duration_time,remaining_time,class,CaseID
0,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,740.958333,1,1
1,0,0,1,0,0,0,0,0,0,0,0,0,118.958333,622.000000,2,1
2,0,0,0,1,0,0,0,0,0,0,0,0,16.000000,606.000000,3,1
3,0,0,0,0,1,0,0,0,0,0,0,0,60.000000,546.000000,4,1
4,0,0,0,0,0,1,0,0,0,0,0,0,546.000000,0.000000,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56383,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,1,15037
56384,0,0,1,0,0,0,0,0,0,0,0,0,0.000000,442.041667,2,15037
56385,0,0,0,1,0,0,0,0,0,0,0,0,6.041667,436.000000,3,15037
56386,0,0,0,0,1,0,0,0,0,0,0,0,60.000000,376.000000,4,15037
56387,0,0,0,0,0,1,0,0,0,0,0,0,376.000000,0.000000,5,15037

In [8]:
dat_group = df.groupby("CaseID")

total_iter = len(dat_group.ngroup())
case_duration_dic = {}
for name, gr in dat_group:
    case_duration_dic[name] = gr['duration_time'].sum()

In [9]:
max(df['duration_time'])

3198.0

In [10]:
case_duration_dic

{1: 740.9583333333333,
 2: 971.0,
 3: 737.9583333333334,
 4: 131.95833333333334,
 5: 751.9583333333334,
 6: 751.9583333333334,
 7: 128.95833333333334,
 8: 128.95833333333334,
 9: 2.0,
 10: 749.9583333333333,
 11: 2.0,
 13: 748.9583333333334,
 14: 754.9583333333334,
 15: 130.95833333333334,
 16: 128.95833333333334,
 17: 128.95833333333334,
 18: 3.0,
 19: 751.9583333333334,
 20: 1.0,
 21: 124.95833333333333,
 22: 3.0,
 23: 3.0,
 24: 0.0,
 25: 120.95833333333333,
 26: 2.9583333333333335,
 27: 7.0,
 28: 3.0,
 29: 723.0,
 30: 682.0,
 31: 82.0,
 32: 628.0,
 33: 123.95833333333333,
 34: 740.9583333333333,
 35: 146.0,
 36: 26.0,
 37: 108.0,
 38: 745.9583333333333,
 39: 742.9583333333333,
 40: 135.95833333333334,
 41: 113.0,
 42: 728.0,
 43: 86.0,
 44: 966.0,
 45: 127.95833333333333,
 46: 4.0,
 47: 19.958333333333332,
 49: 6.0,
 50: 612.0,
 51: 102.04166666666667,
 52: 548.0,
 53: 528.0,
 54: 213.04166666666666,
 56: 739.9583333333333,
 57: 0.9583333333333334,
 58: 3.0,
 59: 136.0,
 60: 735.0,
 61: 729.0,
 63: 725.0,
 64: 7.0,
 65: 722.0,
 66: 718.0,
 67: 0.0,
 68: 109.0,
 69: 715.0,
 70: 711.0,
 71: 702.0,
 73: 713.0,
 74: 126.0,
 75: 122.04166666666667,
 77: 84.0,
 78: 5.0,
 79: 113.0,
 81: 735.9583333333333,
 83: 727.0,
 84: 121.04166666666667,
 85: 121.04166666666667,
 86: 710.0,
 87: 710.0,
 88: 104.0,
 89: 735.0,
 90: 732.0,
 91: 959.0,
 92: 730.0,
 94: 5.0,
 95: 8.0,
 97: 72.0,
 98: 27.0,
 99: 720.0,
 100: 719.0,
 101: 715.0,
 102: 4.0,
 103: 121.04166666666667,
 104: 958.0,
 105: 2.0,
 106: 2.0,
 107: 702.0,
 108: 5.0,
 110: 2.0,
 111: 706.0,
 112: 75.0,
 113: 690.0,
 114: 100.0,
 115: 118.04166666666667,
 116: 197.04166666666666,
 117: 712.0,
 118: 41.0,
 119: 5.0,
 120: 6.0,
 121: 109.0,
 122: 708.0,
 123: 702.0,
 124: 4.0,
 125: 9.0,
 126: 84.0,
 127: 954.0,
 128: 8.0,
 129: 99.0,
 130: 1.0,
 131: 2.0,
 132: 6.0,
 133: 697.0,
 134: 693.0,
 135: 71.0,
 137: 1.0,
 138: 5.0,
 139: 5.0,
 140: 6.0,
 141: 0.0,
 142: 73.0,
 144: 2.0,
 145: 680.0,
 146: 88.0,
 147: 4.0,
 148: 6.0,
 149: 7.0,
 150: 691.0,
 151: 699.0,
 152: 8.0,
 153: 1.0,
 154: 696.0,
 155: 6.0,
 156: 960.0,
 157: 687.0,
 158: 960.0,
 159: 690.0,
 160: 687.0,
 161: 683.0,
 162: 8.0,
 163: 682.0,
 164: 93.0,
 165: 195.04166666666666,
 167: 17.0,
 168: 7.0,
 169: 94.0,
 170: 674.0,
 171: 674.0,
 172: 671.0,
 173: 971.0,
 174: 104.0,
 175: 690.0,
 176: 0.0,
 177: 121.04166666666667,
 178: 6.0,
 179: 87.0,
 180: 105.0,
 181: 6.0,
 182: 673.0,
 183: 81.0,
 184: 79.0,
 186: 689.0,
 187: 67.0,
 188: 68.0,
 189: 1.0,
 190: 651.0,
 191: 650.0,
 192: 669.0,
 194: 14.0,
 195: 0.0,
 196: 91.0,
 197: 200.0,
 198: 748.0,
 199: 159.04166666666666,
 200: 673.0,
 201: 45.0,
 202: 124.04166666666667,
 203: 4.0,
 204: 5.0,
 206: 6.0,
 207: 663.0,
 208: 5.0,
 209: 3.0,
 210: 76.0,
 211: 661.0,
 213: 659.0,
 214: 654.0,
 215: 654.0,
 216: 137.04166666666666,
 217: 22.0,
 218: 113.04166666666667,
 220: 985.9583333333333,
 222: 2.0,
 223: 9.0,
 224: 122.04166666666667,
 225: 9.0,
 226: 657.0,
 227: 140.04166666666666,
 228: 654.0,
 229: 6.0,
 230: 144.04166666666666,
 231: 73.0,
 233: 652.0,
 234: 0.0,
 236: 82.0,
 237: 954.0,
 238: 66.0,
 240: 184.04166666666666,
 241: 78.0,
 242: 78.0,
 243: 954.0,
 244: 76.0,
 245: 661.0,
 246: 6.0,
 247: 652.0,
 249: 1.0,
 250: 7.0,
 251: 655.0,
 252: 653.0,
 253: 953.0,
 254: 657.0,
 255: 649.0,
 256: 61.0,
 257: 646.0,
 258: 646.0,
 260: 1.0,
 261: 115.04166666666667,
 263: 952.0,
 264: 77.0,
 265: 6.0,
 266: 197.04166666666666,
 268: 649.0,
 269: 668.0,
 270: 0.0,
 271: 17.0,
 273: 149.04166666666666,
 274: 662.0,
 276: 668.0,
 277: 80.0,
 279: 982.0,
 280: 665.0,
 281: 4.0,
 282: 975.0,
 284: 1.0,
 287: 643.0,
 288: 129.04166666666666,
 289: 40.0,
 290: 1.0,
 291: 1.0,
 292: 643.0,
 293: 643.0,
 294: 7.0,
 295: 101.04166666666667,
 296: 0.0,
 298: 1.0,
 299: 87.0,
 300: 5.0,
 301: 0.0,
 302: 0.0,
 304: 1.0,
 305: 664.0,
 306: 658.0,
 308: 0.0,
 309: 66.0,
 312: 662.0,
 313: 596.0,
 314: 596.0,
 315: 638.0,
 316: 638.0,
 317: 62.0,
 319: 638.0,
 320: 638.0,
 321: 638.0,
 322: 7.0,
 323: 57.0,
 324: 511.95833333333337,
 325: 39.0,
 326: 876.0,
 328: 1.0,
 329: 627.0,
 330: 110.04166666666667,
 331: 7.0,
 332: 2.0,
 334: 634.0,
 335: 85.0,
 336: 632.0,
 337: 652.0,
 338: 17.0,
 340: 661.0,
 341: 42.0,
 342: 50.0,
 343: 1.0,
 344: 651.0,
 345: 646.0,
 346: 646.0,
 347: 5.0,
 348: 7.0,
 349: 3.0,
 350: 66.0,
 351: 4.0,
 352: 6.0,
 354: 59.0,
 355: 78.0,
 356: 2.0,
 357: 640.0,
 358: 639.0,
 359: 5.0,
 360: 653.0,
 361: 66.0,
 362: 569.0,
 363: 110.04166666666667,
 364: 2.0,
 365: 1.0,
 366: 64.0,
 367: 64.0,
 368: 4.0,
 369: 25.0,
 370: 0.0,
 371: 562.0,
 373: 120.04166666666667,
 374: 120.04166666666667,
 376: 638.0,
 377: 635.0,
 378: 86.0,
 379: 552.0,
 380: 7.0,
 381: 4.0,
 382: 41.0,
 383: 7.0,
 384: 622.0,
 386: 4.0,
 387: 631.0,
 388: 6.0,
 390: 6.0,
 391: 635.0,
 392: 85.0,
 393: 649.0,
 394: 80.0,
 395: 638.0,
 396: 636.0,
 397: 645.0,
 398: 0.0,
 399: 157.04166666666666,
 400: 6.0,
 401: 0.0,
 402: 7.0,
 403: 92.0,
 404: 632.0,
 405: 2.0,
 407: 1.0,
 408: 10.0,
 409: 2.0,
 410: 638.0,
 412: 638.0,
 414: 4.0,
 415: 632.0,
 417: 3.0,
 418: 5.0,
 419: 54.0,
 420: 632.0,
 421: 127.04166666666667,
 422: 7.0,
 423: 8.0,
 424: 83.0,
 425: 67.0,
 426: 6.0,
 427: 2.0,
 428: 78.0,
 429: 642.0,
 430: 4.0,
 431: 0.0,
 432: 598.0,
 434: 624.0,
 435: 624.0,
 436: 624.0,
 437: 603.0,
 439: 592.0,
 441: 589.0,
 442: 584.0,
 443: 122.04166666666667,
 445: 617.0,
 446: 617.0,
 447: 617.0,
 448: 233.0,
 449: 617.0,
 450: 628.0,
 451: 628.0,
 452: 6.0,
 453: 626.0,
 454: 62.0,
 455: 1.0,
 456: 108.04166666666667,
 457: 625.0,
 458: 1188.0,
 459: 624.0,
 460: 636.0,
 461: 70.0,
 462: 634.0,
 463: 84.0,
 464: 632.0,
 465: 3.0,
 466: 48.0,
 467: 6.0,
 468: 625.0,
 469: 129.04166666666666,
 470: 613.0,
 472: 611.0,
 473: 3.0,
 474: 624.0,
 475: 2.0,
 476: 2.0,
 478: 252.0,
 479: 49.0,
 480: 11.0,
 481: 102.04166666666667,
 482: 617.0,
 483: 617.0,
 484: 5.0,
 485: 130.04166666666666,
 486: 2.0,
 487: 620.0,
 488: 56.0,
 489: 5.0,
 490: 618.0,
 491: 617.0,
 492: 617.0,
 493: 19.0,
 494: 3.0,
 495: 607.0,
 496: 610.0,
 497: 4.0,
 498: 629.0,
 499: 27.0,
 501: 959.0,
 502: 129.04166666666666,
 503: 630.0,
 504: 958.0,
 505: 629.0,
 506: 1.0,
 507: 129.04166666666666,
 508: 408.95833333333337,
 509: 7.0,
 510: 612.0,
 511: 0.0,
 512: 235.04166666666666,
 513: 2.0,
 514: 610.0,
 515: 2.0,
 516: 624.0,
 517: 60.0,
 519: 107.04166666666667,
 520: 115.04166666666667,
 521: 588.0,
 522: 584.0,
 523: 48.0,
 524: 113.04166666666667,
 525: 6.0,
 526: 119.04166666666667,
 527: 591.0,
 528: 4.0,
 529: 614.0,
 530: 137.04166666666666,
 531: 3.0,
 532: 610.0,
 533: 5.0,
 534: 25.0,
 535: 123.04166666666667,
 537: 3.0,
 538: 26.0,
 539: 648.0,
 541: 625.0,
 542: 615.0,
 543: 105.04166666666667,
 545: 607.0,
 546: 106.04166666666667,
 548: 3.0,
 549: 1.0,
 550: 17.0,
 551: 0.0,
 552: 117.04166666666667,
 553: 104.0,
 554: 83.0,
 555: 610.0,
 556: 15.0,
 557: 2.0,
 558: 591.0,
 559: 590.0,
 560: 115.04166666666667,
 561: 115.04166666666667,
 562: 131.04166666666666,
 564: 114.04166666666667,
 566: 223.0,
 567: 128.04166666666666,
 568: 620.0,
 569: 7.0,
 570: 0.0,
 571: 616.0,
 572: 8.0,
 573: 616.0,
 574: 612.0,
 575: 10.0,
 576: 101.04166666666667,
 577: 617.0,
 578: 96.0,
 580: 642.0,
 582: 134.04166666666666,
 583: 45.0,
 584: 603.0,
 585: 596.0,
 586: 5.0,
 587: 596.0,
 588: 0.0,
 589: 137.04166666666666,
 590: 1.0,
 591: 1.0,
 592: 561.0,
 593: 607.0,
 594: 606.0,
 596: 604.0,
 597: 6.0,
 598: 607.0,
 599: 130.04166666666666,
 600: 46.0,
 601: 610.0,
 602: 261.0,
 603: 2.0,
 604: 587.0,
 606: 577.0,
 607: 594.0,
 608: 592.0,
 609: 592.0,
 610: 96.0,
 611: 633.0,
 612: 627.0,
 613: 7.0,
 614: 0.0,
 615: 120.04166666666667,
 616: 554.0,
 617: 117.04166666666667,
 618: 2.0,
 619: 8.0,
 620: 37.0,
 622: 3.0,
 623: 6.0,
 624: 600.0,
 625: 498.95833333333337,
 626: 494.95833333333337,
 629: 6.0,
 630: 1.0,
 631: 15.0,
 632: 603.0,
 633: 26.0,
 635: 847.0,
 637: 5.0,
 638: 46.0,
 639: 46.0,
 640: 0.0,
 641: 123.04166666666667,
 642: 579.0,
 643: 0.0,
 646: 596.0,
 647: 118.04166666666667,
 648: 20.0,
 649: 25.0,
 650: 30.0,
 651: 40.0,
 652: 7.0,
 653: 38.0,
 654: 19.0,
 655: 33.0,
 656: 3.0,
 657: 570.0,
 658: 215.0,
 659: 561.0,
 661: 608.0,
 662: 573.0,
 663: 5.0,
 664: 110.04166666666667,
 665: 560.0,
 666: 116.04166666666667,
 667: 114.04166666666667,
 668: 584.0,
 669: 591.0,
 671: 6.0,
 672: 114.04166666666667,
 673: 5.0,
 675: 0.0,
 676: 26.0,
 677: 590.0,
 678: 606.0,
 679: 51.0,
 680: 603.0,
 681: 187.04166666666666,
 682: 843.0,
 683: 3.0,
 684: 656.9583333333334,
 685: 3.0,
 686: 585.0,
 689: 583.0,
 691: 587.0,
 692: 238.0,
 693: 2.0,
 694: 597.0,
 695: 597.0,
 696: 116.04166666666667,
 697: 597.0,
 698: 2.0,
 699: 596.0,
 700: 13.0,
 701: 1596.0416666666667,
 702: 2.0,
 703: 26.0,
 704: 0.0,
 705: 590.0,
 706: 1.0,
 707: 128.04166666666666,
 708: 589.0,
 709: 7.0,
 710: 20.0,
 711: 582.0,
 712: 580.0,
 713: 27.0,
 714: 607.0,
 715: 949.0,
 716: 119.04166666666667,
 717: 3.0,
 718: 3.0,
 720: 7.0,
 721: 499.95833333333337,
 722: 474.95833333333337,
 723: 466.95833333333337,
 724: 9.0,
 725: 127.04166666666667,
 726: 72.04166666666667,
 727: 121.04166666666667,
 728: 65.04166666666667,
 729: 119.04166666666667,
 730: 1120.0,
 731: 115.04166666666667,
 732: 120.04166666666667,
 735: 0.0,
 736: 3.0,
 737: 838.0,
 739: 15.0,
 740: 835.0,
 741: 68.0,
 742: 48.0,
 743: 579.0,
 744: 564.0,
 745: 140.95833333333334,
 746: 4.0,
 747: 589.9583333333333,
 748: 0.0,
 749: 533.0,
 750: 6.0,
 751: 5.0,
 752: 4.0,
 753: 546.0,
 754: 6.0,
 755: 7.0,
 756: 7.0,
 757: 539.0,
 758: 113.04166666666667,
 759: 5.0,
 760: 111.04166666666667,
 761: 96.04166666666667,
 762: 20.0,
 763: 2.0,
 764: 538.0,
 765: 110.04166666666667,
 766: 8.0,
 767: 524.0,
 768: 3.0416666666666665,
 769: 6.0,
 770: 109.04166666666667,
 771: 530.0,
 772: 91.04166666666667,
 773: 1.0,
 774: 130.04166666666666,
 775: 9.0,
 776: 94.04166666666667,
 777: 93.04166666666667,
 778: 1091.0,
 779: 84.04166666666667,
 780: 517.9583333333334,
 781: 514.9583333333334,
 782: 7.0,
 783: 100.04166666666667,
 784: 2.0,
 785: 90.0,
 786: 1.0,
 787: 4.0,
 788: 1.0,
 790: 82.04166666666667,
 791: 89.0,
 792: 7.0,
 793: 1.0,
 794: 949.0,
 795: 488.95833333333337,
 796: 532.0,
 797: 2.0,
 798: 6.0,
 799: 2.0,
 800: 503.95833333333337,
 801: 28.0,
 802: 0.0,
 803: 5.0,
 804: 497.95833333333337,
 805: 197.95833333333334,
 806: 107.04166666666667,
 807: 73.0,
 809: 6.0,
 810: 76.04166666666667,
 811: 4.041666666666667,
 812: 520.0,
 813: 71.0,
 814: 58.0,
 815: 2.0,
 816: 57.0,
 817: 1.0,
 818: 0.0,
 819: 1.0,
 820: 26.0,
 821: 104.04166666666667,
 822: 940.0,
 823: 7.0,
 824: 440.95833333333337,
 825: 1058.9583333333335,
 826: 4.0,
 827: 939.0,
 828: 515.9583333333334,
 829: 1514.0,
 831: 6.0,
 832: 9.0,
 833: 424.95833333333337,
 834: 969.9583333333333,
 835: 0.0,
 836: 5.0,
 837: 951.0,
 839: 8.0,
 840: 9.0,
 841: 21.0,
 842: 72.0,
 843: 7.0,
 844: 113.04166666666667,
 845: 500.95833333333337,
 846: 1.0,
 847: 223.0,
 848: 0.0,
 849: 409.95833333333337,
 850: 970.9583333333333,
 851: 962.9583333333333,
 852: 944.9583333333333,
 853: 0.0,
 854: 8.0,
 856: 417.9583333333333,
 857: 2.0,
 858: 406.95833333333337,
 859: 3.0,
 860: 106.95833333333333,
 861: 146.95833333333334,
 862: 4.0,
 864: 5.0,
 866: 18.0,
 867: 6.0,
 869: 40.958333333333336,
 870: 385.95833333333337,
 871: 925.0,
 872: 0.0,
 873: 1.0,
 874: 442.95833333333337,
 875: 433.95833333333337,
 876: 943.0,
 877: 56.958333333333336,
 880: 2.0,
 881: 500.95833333333337,
 882: 72.0,
 883: 51.0,
 885: 884.9583333333333,
 887: 66.95833333333333,
 888: 7.0,
 889: 74.0,
 890: 6.0,
 891: 986.9583333333334,
 892: 422.9583333333333,
 893: 11.0,
 894: 417.9583333333333,
 895: 416.9583333333333,
 896: 66.0,
 897: 926.0,
 898: 59.0,
 899: 915.0,
 900: 83.0,
 902: 454.95833333333337,
 903: 439.95833333333337,
 904: 101.04166666666667,
 905: 437.95833333333337,
 906: 44.0,
 907: 2.0,
 908: 3.0,
 909: 894.0,
 910: 0.0,
 911: 933.0,
 912: 3.0,
 913: 910.0,
 915: 82.0,
 916: 902.0,
 917: 36.0,
 918: 70.0,
 919: 494.95833333333337,
 920: 31.0,
 921: 1.0,
 922: 3.0,
 923: 53.0,
 924: 47.0,
 925: 63.0,
 927: 154.95833333333334,
 928: 960.9583333333333,
 929: 4.0,
 930: 1.0,
 931: 92.95833333333333,
 932: 6.0,
 933: 4.0,
 934: 44.0,
 935: 66.95833333333333,
 937: 0.0,
 938: 486.95833333333337,
 940: 1.0,
 941: 437.95833333333337,
 942: 435.95833333333337,
 943: 39.0,
 944: 5.0,
 945: 431.95833333333337,
 946: 480.95833333333337,
 947: 1.0,
 948: 37.0,
 949: 430.95833333333337,
 950: 937.0,
 951: 61.0,
 953: 471.95833333333337,
 954: 5.0,
 955: 461.95833333333337,
 956: 7.0,
 958: 407.95833333333337,
 959: 9.0,
 960: 1004.9583333333334,
 961: 422.9583333333333,
 963: 383.95833333333337,
 964: 930.9583333333333,
 965: 906.0,
 966: 0.0,
 967: 3.0,
 968: 2.0,
 969: 405.95833333333337,
 970: 963.9583333333333,
 971: 125.04166666666667,
 972: 261.95833333333337,
 973: 144.95833333333334,
 974: 4.0,
 975: 455.95833333333337,
 976: 455.95833333333337,
 977: 47.0,
 978: 0.0,
 979: 418.9583333333333,
 980: 411.9583333333333,
 981: 47.958333333333336,
 982: 957.9583333333333,
 984: 18.0,
 985: 0.0,
 986: 113.04166666666667,
 987: 398.95833333333337,
 988: 1.0,
 989: 5.0,
 990: 382.95833333333337,
 991: 383.95833333333337,
 992: 26.958333333333332,
 993: 939.9583333333333,
 996: 838.0,
 997: 3.0,
 998: 3.0,
 999: 377.9583333333333,
 1000: 260.0,
 1002: 1.0,
 1003: 881.0,
 1004: 3.0,
 1005: 436.95833333333337,
 1006: 432.95833333333337,
 1007: 3.0,
 1008: 4.0,
 1009: 49.958333333333336,
 1010: 5.0,
 1011: 134.95833333333334,
 1012: 86.95833333333333,
 1013: 945.9583333333333,
 1014: 0.0,
 1016: 942.9583333333333,
 1017: 942.9583333333333,
 1018: 927.0,
 1021: 1.0,
 1022: 823.0,
 1023: 11.958333333333334,
 1024: 9.958333333333334,
 1025: 922.0,
 1027: 36.0,
 1028: 0.0,
 1029: 925.0,
 1030: 116.04166666666667,
 1031: 2.9583333333333335,
 1032: 3.9583333333333335,
 1033: 2.0,
 1035: 952.0,
 1036: 903.0,
 1037: 1.0,
 1038: 0.0,
 1039: 845.0,
 1040: 2.0,
 1041: 17.0,
 1043: 50.0,
 1044: 0.0,
 1045: 2.0,
 1046: 802.0,
 1048: 58.0,
 1050: 85.0,
 1051: 803.0,
 1052: 707.9583333333334,
 1053: 112.04166666666667,
 1054: 54.0,
 1055: 1.0,
 1056: 948.0,
 1057: 4.0,
 1058: 5.0,
 1059: 874.0,
 1060: 911.0,
 1061: 48.0,
 1062: 0.0,
 1063: 906.0,
 1064: 518.0,
 1065: 903.0,
 1066: 1.0,
 1067: 144.95833333333334,
 1068: 5.0,
 1070: 1.0,
 1071: 8.0,
 1072: 5.0,
 1074: 0.0,
 1075: 895.0,
 1078: 957.9583333333333,
 1079: 3.0,
 1080: 0.0,
 1081: 5.0,
 1082: 3.0,
 1083: 57.0,
 1084: 4.0,
 1085: 1.0,
 1086: 3.0,
 1087: 950.9583333333333,
 1088: 11.0,
 1089: 940.9583333333333,
 1090: 75.95833333333333,
 1091: 75.95833333333333,
 1092: 12.958333333333334,
 1094: 0.0,
 1095: 926.0,
 1096: 5.0,
 1097: 20.0,
 1100: 8.0,
 1101: 6.0,
 1102: 112.04166666666667,
 1103: 3.0,
 1104: 914.0,
 1105: 949.0,
 1106: 95.0,
 1107: 918.0,
 1108: 0.0,
 1109: 2.0,
 1110: 0.0,
 1111: 0.0,
 1112: 2.0,
 1113: 898.0,
 1114: 82.0,
 1115: 37.0,
 1116: 38.0,
 1117: 50.0,
 1119: 1064.0,
 1120: 1045.0,
 1121: 858.0,
 1122: 19.0,
 1123: 961.0,
 1124: 92.95833333333333,
 1125: 7.0,
 1126: 1.0,
 ...}

reference for calulating quartile [here](http://web.mnstate.edu/peil/MDEV102/U4/S36/S363.html#:~:text=The%20third%20quartile%2C%20denoted%20by,25%25%20lie%20above%20Q3%20)

In [11]:
mean(case_duration_dic.values())

342.40857926974786

In [12]:
# quartile calculation
import statistics
def calc_third_quartile(lis):
    lis.sort()
    size = len(lis)
    lis_upper_half = lis[size//2:-1]
    third_quartile = statistics.median(lis_upper_half)
    return third_quartile
    
case_durations = list(case_duration_dic.values())
third_quartile  = calc_third_quartile(case_durations)

In [13]:
third_quartile

621.0416666666667

### Filter dataset for RL model

In [14]:
cases_gs = []
cases_gv = []
for k,v in case_duration_dic.items():
    if v <= third_quartile:
        cases_gs.append(k)
    else:
        cases_gv.append(k)

In [15]:
len(cases_gs), len(cases_gv)

(9429, 3142)

In [16]:
tot = len(cases_gs)+ len(cases_gv)
percent_gs_cases = len(cases_gs) / tot
print(percent_gs_cases)

0.750059661124811

In [17]:
cases_train = cases_gs
cases_test = cases_gv

In [18]:
df.shape, len(cases_train),  len(cases_test)

((43364, 16), 9429, 3142)

In [19]:
data_train = df.loc[df['CaseID'].isin(cases_train)]
data_test = df.loc[df['CaseID'].isin(cases_test)]

In [20]:
data_train

,0,1,2,3,4,5,6,7,8,9,10,11,duration_time,remaining_time,class,CaseID
15,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,131.958333,1,4
16,0,0,1,0,0,0,0,0,0,0,0,0,131.958333,0.000000,2,4
27,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,128.958333,1,7
28,0,0,1,0,0,0,0,0,0,0,0,0,128.958333,0.000000,2,7
29,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,128.958333,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56383,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,1,15037
56384,0,0,1,0,0,0,0,0,0,0,0,0,0.000000,442.041667,2,15037
56385,0,0,0,1,0,0,0,0,0,0,0,0,6.041667,436.000000,3,15037
56386,0,0,0,0,1,0,0,0,0,0,0,0,60.000000,376.000000,4,15037
56387,0,0,0,0,0,1,0,0,0,0,0,0,376.000000,0.000000,5,15037

In [21]:
data_test

,0,1,2,3,4,5,6,7,8,9,10,11,duration_time,remaining_time,class,CaseID
0,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,740.958333,1,1
1,0,0,1,0,0,0,0,0,0,0,0,0,118.958333,622.000000,2,1
2,0,0,0,1,0,0,0,0,0,0,0,0,16.000000,606.000000,3,1
3,0,0,0,0,1,0,0,0,0,0,0,0,60.000000,546.000000,4,1
4,0,0,0,0,0,1,0,0,0,0,0,0,546.000000,0.000000,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56364,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,1280.041667,1,15032
56365,0,0,1,0,0,0,0,0,0,0,0,0,58.000000,1222.041667,2,15032
56366,0,0,0,1,0,0,0,0,0,0,0,0,10.041667,1212.000000,3,15032
56367,0,0,0,0,1,0,0,0,0,0,0,0,60.000000,1152.000000,4,15032
56368,0,0,0,0,0,1,0,0,0,0,0,0,1152.000000,0.000000,5,15032

## Analysing unique events

In [22]:
a = get_unique_act(data_train)

In [23]:
len(a)

12

In [24]:
tot = get_unique_act(df)
len(tot)

12

In [25]:
lis = []
for act in tot:
    if act not in a:
        lis.append(act)
lis

[]

In [26]:
for act in lis:
    df_sub = df[df["class"] == act]
    caseid_lis = list(df_sub["CaseID"])
    l = len(caseid_lis)
    caseid_sel = caseid_lis[:l//2]
    if len(caseid_sel) == 0:
        caseid_sel = caseid_lis
        
    r = df.loc[df['CaseID'].isin(caseid_sel)]
    data_train = data_train.append(r)

In [27]:
data_train

,0,1,2,3,4,5,6,7,8,9,10,11,duration_time,remaining_time,class,CaseID
15,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,131.958333,1,4
16,0,0,1,0,0,0,0,0,0,0,0,0,131.958333,0.000000,2,4
27,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,128.958333,1,7
28,0,0,1,0,0,0,0,0,0,0,0,0,128.958333,0.000000,2,7
29,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,128.958333,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56383,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,1,15037
56384,0,0,1,0,0,0,0,0,0,0,0,0,0.000000,442.041667,2,15037
56385,0,0,0,1,0,0,0,0,0,0,0,0,6.041667,436.000000,3,15037
56386,0,0,0,0,1,0,0,0,0,0,0,0,60.000000,376.000000,4,15037
56387,0,0,0,0,0,1,0,0,0,0,0,0,376.000000,0.000000,5,15037

In [28]:
len(get_unique_act(data_train)), len(get_unique_act(data_test))

(12, 12)

In [29]:
len(get_unique_act(df))

12

In [30]:

name = dataset+'_d0'
pickle.dump(data_train, open(name+"_train_RL.pkl", "wb"))
pickle.dump(data_test, open(name+"_test_RL.pkl", "wb"))